### ISSUE TITLE
Only some commands work

### ISSUE THREAD

**Issue by elbowz** [dankinsoid/IdeaVimMulticursor#6]
Maybe, I'm missing something, but command like: `mcv`, `mcr`, `mci(` don't seem to work.

In the `idea.log` I don't see anything 

`ms/print` work like expected

**Comment by dankinsoid** [comment]
@elbowz Hi, yes I supported only some commands: /, f, t, w, W, b, B, e, E
How would you expect mcv, mcr and mci to work?

**Comment by elbowz** [comment]
> How would you expect mcv, mcr and mci to work?

- `mcv`: add a caret on the current position (the [same behavior Intellij does](https://www.jetbrains.com/help/idea/multicursor.html#add-carets-at-selected-locations))
- `mcr`: not clear the difference between real and virtual, but on my IDE it simply "replace" the character (vim behaviour)
- `mci(`: in an example string like `this is (ex|ample) string` with '|' represent the current caret I expect to have: `this is (|example|) string`, just two carets, one after '(' and 

I hope to be clear

thanks!

**Comment by torbenf** [comment]
The README is not very clear. I too don't know how to properly use `mcv`, `mcr` and `mci`.
More examples would be very useful. 
`ms/print` works as expected but what is a virtual and a real caret?

**Comment by dankinsoid** [comment]
@torbenf yes, I should update the readme, and it looks like some commands are broken in the new versions of the IDE.  
I implemented a virtual caret to allow adding multiple carets manually in vim: you create virtual carets and then use mcr to make them real (regular) carets. However, I'm not sure if this feature is useful now, since the IDE itself allows [adding a caret with the keyboard](https://www.jetbrains.com/help/idea/multicursor.html#add-carets-at-each-line-of-the-current-document).

**Comment by reinierbutot** [comment]
also pressing escape in the latest version does not remove the created cursors. i have to manually click with the mouse somewhere to get rid of them.

**Comment by kuchejak** [comment]
For me the most important commands not working are `mc^` nor `mc$`. Also when I press backspace while entering search term in `mc/`, the inputed text does not get deleted. 

Webstorm 2024.2.4 (Macbook)

Other than that I love the idea of this plugin! It's like a superpower in certain cases.

**Comment by dankinsoid** [comment]
@elbowz @kuchejak  @reinierbutot  check update

**Comment by kuchejak** [comment]
@dankinsoid I have tried `mc^` and `mc$` in the version 1.3.2 but it still does not work for me.
